services:
  - type: web
    name: landing-page-professora-mvp
    env: node
    plan: free
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: ADMIN_EMAIL
        value: admin@professora.local
      - key: ADMIN_PASSWORD
        value: prof123
      - key: WHATSAPP_GROUP_URL
        sync: false
      - key: SIGNATURE_BASE_URL
        sync: false
